version: '3'

volumes:
  document_data:
  document_log:
  app_data:

  nextcloud_db:
    image: postgres:alpine
    container_name: nextcloud_db
    restart: always
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    env_file:
      - db.env
      
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    expose:
      - '9000'
      - '443'
    volumes:
      - app_data:/var/www/html
      - /usr/bin/nano:/usr/bin/nano
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu
    environment:
      - POSTGRES_HOST=nextcloud_db
    env_file:
      - db.env
    depends_on:
      - nextcloud_db

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - '80'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /opt/certs:/opt/certs
      - app_data:/var/www/html
      
